[variables]
  NODE_ENV = "production"

[phases.setup]
  nixPkgs = ["nodejs", "npm", "qpdf"]

[phases.install]
  cmds = [
    "npm cache clean --force",
    "npm ci --omit=dev --no-cache"
  ]

[phases.build]
  cmds = ["echo 'No build step required'"]

[start]
  cmd = "npm start" 