[variables]
  NODE_ENV = "production"

[phases.setup]
  nixPkgs = ["nodejs", "qpdf", "python3", "gcc", "gnumake", "pkg-config", "vips"]

[phases.install]
  cmds = [
    "npm install --production"
  ]

[phases.build]
  cmds = ["echo 'No build step required'"]

[start]
  cmd = "npm start" 