[variables]
  NODE_ENV = "production"

[phases.setup]
  nixPkgs = ["nodejs", "qpdf", "python3", "gcc", "gnumake", "pkg-config", "vips-dev", "glib-dev"]

[phases.install]
  cmds = [
    "npm config set loglevel verbose",
    "npm install --production --verbose --platform=linux --arch=x64"
  ]

[phases.build]
  cmds = ["echo 'No build step required'"]

[start]
  cmd = "npm start" 