[variables]
  NODE_ENV = "production"

[phases.setup]
  nixPkgs = ["nodejs", "qpdf"]

[phases.install]
  cmds = [
    "npm ci --omit=dev --no-cache --prefer-offline"
  ]

[phases.build]
  cmds = ["echo 'No build step required'"]

[start]
  cmd = "npm start" 